"""Shared enums used across models and schemas."""
import enum


class RecordStatus(str, enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class MatchStatus(str, enum.Enum):
    MATCHED = "MATCHED"
    EXCEPTION = "EXCEPTION"
    UNMATCHED = "UNMATCHED"


class MatchMethod(str, enum.Enum):
    EXACT_REFERENCE = "EXACT_REFERENCE"
    INVOICE_CUSTOMER_AMOUNT = "INVOICE_CUSTOMER_AMOUNT"
    INVOICE_AMOUNT_DATE_TOLERANCE = "INVOICE_AMOUNT_DATE_TOLERANCE"
    CUSTOMER_AMOUNT_DATE_PROXIMITY = "CUSTOMER_AMOUNT_DATE_PROXIMITY"
    FUZZY = "FUZZY"
    NONE = "NONE"


class ExceptionType(str, enum.Enum):
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    MISSING_BANK_SETTLEMENT = "MISSING_BANK_SETTLEMENT"
    MISSING_LEDGER_ENTRY = "MISSING_LEDGER_ENTRY"
    DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION"
    PARTIAL_SETTLEMENT = "PARTIAL_SETTLEMENT"
    FEE_MISMATCH = "FEE_MISMATCH"
    TAX_MISMATCH = "TAX_MISMATCH"
    UNKNOWN_UNRESOLVABLE = "UNKNOWN_UNRESOLVABLE"


class Severity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ExceptionStatus(str, enum.Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ResolutionAction(str, enum.Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_INVESTIGATION = "REQUEST_INVESTIGATION"
    MARK_UNRESOLVED = "MARK_UNRESOLVED"
